// src/app/about/page.tsx
'use client';

import FadeInWrapper from '@/components/FadeInWrapper';
import Image from 'next/image';

// Helper for SVG icons, can be expanded or replaced with a proper icon library
const InfoIcon = ({ pathData, size = 'is-medium' }: { pathData: string, size?: string }) => (
  <span className={`icon ${size} has-text-success`}>
    <svg viewBox="0 0 24 24" fill="currentColor">
      <path d={pathData}></path>
    </svg>
  </span>
);

interface Certification {
  title: string;
  issuer: string;
  icon: string;
  color: string;
  credlyUrl?: string;
}

export default function AboutPage() {
  const processSteps = [
    {
      title: "1. Requirements Analysis",
      description: "I begin by thoroughly understanding project requirements, user needs, and business objectives to create a comprehensive development strategy.",
      icon: "M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
    },{
      title: "2. Architecture & Design",
      description: "I design scalable system architecture and create intuitive user interfaces, focusing on both performance and user experience.",
      icon: "M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM4 13a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H5a1 1 0 01-1-1v-6zM16 13a1 1 0 011-1h2a1 1 0 011 1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-6z"
    },{
      title: "3. Development & Implementation",
      description: "I write clean, maintainable code using modern best practices, with emphasis on security, performance, and scalability.",
      icon: "M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"
    },{
      title: "4. Testing & Deployment",
      description: "I conduct comprehensive testing and manage deployment processes, ensuring robust, reliable production-ready applications.",
      icon: "M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"
  }];

  const whyChooseUsItems = [
    {
      title: "Technical Excellence",
      description: "I deliver high-quality, scalable solutions using industry best practices and cutting-edge technologies to ensure optimal performance and maintainability.",
      icon: "M13 10V3L4 14h7v7l9-11h-7z"
    },{
      title: "User-Centric Approach",
      description: "Every project begins with understanding the end user. I create intuitive, accessible interfaces that provide exceptional user experiences.",
      icon: "M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"
    },{
      title: "Agile Development",
      description: "I follow agile methodologies with clear communication, regular updates, and iterative development to deliver projects on time and budget.",
      icon: "M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
    },{
      title: "Continuous Innovation",
      description: "I stay current with emerging technologies and industry trends, continuously improving my skills to deliver modern, future-proof solutions.",
      icon: "M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
  }];

  const education = [
    {
      degree: "Master of Science in Software Engineering",
      school: "University of Wisconsin-La Crosse",
      year: "Expected 2028",
      description: "Advanced software development methodologies, system architecture, and project management."
    },
    {
      degree: "Bachelor of Science in Computer Programming",
      school: "University of Wisconsin-La Crosse",
      year: "Expected 2027",
      description: "Comprehensive foundation in programming languages, algorithms, and software development principles."
    }
  ];

  const certifications: Certification[] = [
    {
      title: "Microsoft Office Specialist",
      issuer: "Microsoft Certified",
      icon: "📄",
      color: "#0078D4",
      credlyUrl: "https://www.credly.com/badges/a53e0814-7906-43fc-99aa-87ca2d203a6e/public_url"
    },
    {
      title: "Microsoft Word Specialist",
      issuer: "Microsoft Certified",
      icon: "📝",
      color: "#2B579A",
      credlyUrl: "https://www.credly.com/badges/397e3a70-ab52-4d53-9025-10beb9a80472/public_url"
    },
    {
      title: "Microsoft Excel Specialist",
      issuer: "Microsoft Certified",
      icon: "📊",
      color: "#217346",
      credlyUrl: "https://www.credly.com/badges/ac9b7a98-01df-4160-ab5c-b706f28120ff/public_url"
    },
    {
      title: "Microsoft PowerPoint Specialist",
      issuer: "Microsoft Certified",
      icon: "📽️",
      color: "#D24726",
      credlyUrl: "https://www.credly.com/badges/836e8596-1ad6-4190-a2b1-37f9183b6602/public_url"
    },
    {
      title: "Full-Stack Developer",
      issuer: "Professional Experience",
      icon: "💻",
      color: "#48c774"
    },
    {
      title: "Database Management",
      issuer: "MySQL & SQL",
      icon: "🗄️",
      color: "#3273dc"
    },
    {
      title: "AI Integration Specialist",
      issuer: "LLM & API Integration",
      icon: "🤖",
      color: "#e85d04"
    },
    {
      title: "Modern Web Development",
      issuer: "React & Next.js",
      icon: "⚛️",
      color: "#61dafb"
    }
  ];

  const technicalStrengths = [
    {
      category: "Frontend Development",
      skills: ["React", "Next.js", "TypeScript", "JavaScript", "HTML5/CSS3", "Responsive Design"],
      icon: "🎨"
    },
    {
      category: "Backend Development",
      skills: ["Node.js", "Express", "Python", "RESTful APIs", "Server Architecture"],
      icon: "⚙️"
    },
    {
      category: "Database & Data",
      skills: ["MySQL", "Database Design", "SQL Optimization", "Data Modeling"],
      icon: "📊"
    },
    {
      category: "AI & Modern Tools",
      skills: ["LLM Integration", "Prompt Engineering", "API Integration", "AI-Assisted Development"],
      icon: "🚀"
    },
    {
      category: "Development Practices",
      skills: ["Git/GitHub", "Agile Methodology", "Code Review", "Testing", "Documentation"],
      icon: "🔧"
    }
  ];

  const bubbleStyle: React.CSSProperties = {
    background: 'radial-gradient(circle, rgba(44, 44, 44, 0.8) 0%, rgba(26, 26, 26, 0.9) 100%)',
    backdropFilter: 'blur(10px)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '20px',
    boxShadow: '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
    padding: '3rem',
    marginBottom: '2rem'
  };

  return (
    <div className="section">
          <div className="container">

        <FadeInWrapper translateY={30}>
          <div className="box" style={{...bubbleStyle, textAlign: 'center'}}>
            <h1 className="title is-1 is-spaced" style={{color: 'white'}}>About Carter Moyer</h1>
            <p className="subtitle is-4" style={{color: '#a0a0a0'}}>
              Full-Stack Software Engineer | Problem Solver | Innovation Enthusiast
            </p>
            <div style={{ marginTop: '1.5rem' }}>
              <span style={{ color: '#e85d04', fontSize: '1.1rem', fontWeight: '600' }}>📍 Fond du Lac, WI</span>
              <span style={{ color: '#a0a0a0', margin: '0 1rem' }}>•</span>
              <span style={{ color: '#e85d04', fontSize: '1.1rem', fontWeight: '600' }}>🎓 Computer Science Graduate Student</span>
            </div>
          </div>
        </FadeInWrapper>

        <FadeInWrapper translateY={30} delay={100}>
          <div className="box" style={bubbleStyle}>
              <h2 className="title is-3 has-text-success-dark has-text-centered-mobile mb-5">Professional Philosophy</h2>
              <div className="content is-medium">
              <p style={{color: '#f0f0f0', lineHeight: '1.7', marginBottom: '1.5rem'}}>
                  I believe exceptional software is created at the intersection of technical excellence and human-centered design. My approach combines rigorous engineering practices with deep empathy for user needs, resulting in solutions that are not only functionally robust but genuinely valuable to those who use them.
                </p>
                <p style={{color: '#f0f0f0', lineHeight: '1.7'}}>
                  Every line of code I write is guided by principles of clarity, maintainability, and performance. I&apos;m passionate about creating digital experiences that solve real problems while pushing the boundaries of what&apos;s possible with modern web technologies.
                </p>
            </div>
          </div>
        </FadeInWrapper>

        <FadeInWrapper translateY={30} delay={200}>
          <div className="box" style={bubbleStyle}>
              <h2 className="title is-3 has-text-centered mb-6 has-text-success-dark">Who I Am</h2>
              <div className="columns is-vcentered is-multiline">
                <div className="column is-one-third has-text-centered">
                <figure className="image is-256x256 mb-4 image-bubble">
                    <Image 
                      src="/images/profile.jpg"
                      alt="A photo of Carter Moyer"
                      width={256}
                      height={256}
                      priority
                    />
                  </figure>
                </div>
                <div className="column is-two-thirds">
                  <h3 className="title is-4 has-text-success">Carter Moyer</h3>
                <p className="subtitle is-6 is-italic mb-4" style={{color: '#a0a0a0'}}>Full-Stack Software Engineer</p>
                  <div className="content">
                  <p style={{color: '#f0f0f0', lineHeight: '1.6', marginBottom: '1.2rem'}}>
                      I&apos;m a dedicated software engineer with a passion for transforming complex challenges into elegant, user-friendly solutions. Based in Fond du Lac, Wisconsin, I bring a unique blend of technical expertise and creative problem-solving to every project I undertake.
                    </p>
                    <p style={{color: '#f0f0f0', lineHeight: '1.6', marginBottom: '1.2rem'}}>
                      Currently pursuing advanced degrees in Computer Programming and Software Engineering at the University of Wisconsin-La Crosse, I combine academic rigor with practical experience to deliver cutting-edge web applications and digital solutions.
                    </p>
                    <p style={{color: '#f0f0f0', lineHeight: '1.6', marginBottom: '1.2rem'}}>
                      My expertise spans frontend and backend development, with strong skills in React, JavaScript/TypeScript, Python, Java, and MySQL databases. I&apos;m particularly passionate about creating clean, efficient code and building user-friendly web applications.
                    </p>
                    <p style={{color: '#f0f0f0', lineHeight: '1.6', marginBottom: '1.2rem'}}>
                      I have hands-on experience integrating AI technologies, including Large Language Models (LLMs), into production applications. From crafting effective prompts to building robust API integrations, I leverage AI as a practical tool to enhance functionality and user experience. My work includes implementing intelligent features, optimizing AI responses, and ensuring reliable performance in real-world applications.
                    </p>
                    <p style={{color: '#f0f0f0', lineHeight: '1.6'}}>
                      Beyond traditional development, I specialize in prompt engineering and AI-assisted development workflows, utilizing tools like Cursor AI to accelerate development while maintaining code quality. I understand how to prevent AI hallucinations, structure projects for scalability, and implement best practices that keep systems maintainable and efficient.
                    </p>
                </div>
              </div>
            </div>
          </div>
        </FadeInWrapper>

        <FadeInWrapper translateY={30} delay={300}>
          <div className="box" style={bubbleStyle}>
              <h2 className="title is-3 has-text-success-dark has-text-centered mb-6">My Process & Skills</h2>
              <div className="columns is-multiline is-variable is-4">
                {processSteps.map((step, index) => (
                  <div key={index} className="column is-half">
                    <article className="media">
                      <figure className="media-left">
                        <InfoIcon pathData={step.icon} />
                      </figure>
                      <div className="media-content">
                        <div className="content">
                        <p style={{color: '#f0f0f0'}}>
                            <strong className="has-text-success-dark">{step.title}</strong>
                            <br />
                            {step.description}
                          </p>
                        </div>
                      </div>
                    </article>
                  </div>
                ))}
            </div>
          </div>
        </FadeInWrapper>

        <FadeInWrapper translateY={30} delay={400}>
          <div className="box" style={bubbleStyle}>
              <h2 className="title is-3 has-text-success-dark has-text-centered mb-6">Why Choose Me</h2>
              <div className="columns is-multiline is-variable is-4">
                {whyChooseUsItems.map((item, index) => (
                    <div key={index} className="column is-half">
                         <article className="media">
                            <figure className="media-left">
                                <InfoIcon pathData={item.icon} />
                            </figure>
                            <div className="media-content">
                                <div className="content">
                              <p style={{color: '#f0f0f0'}}>
                                    <strong className="has-text-success-dark">{item.title}</strong>
                                    <br />
                                    {item.description}
                                </p>
                                </div>
                            </div>
                        </article>
                    </div>
                ))}
            </div>
          </div>
        </FadeInWrapper>

        <FadeInWrapper translateY={30} delay={450}>
          <div className="box" style={bubbleStyle}>
            <h2 className="title is-3 has-text-success-dark has-text-centered mb-6">Technical Strengths & Core Competencies</h2>
            <p className="has-text-centered mb-5" style={{color: '#a0a0a0', fontSize: '1.1rem'}}>
              A comprehensive overview of my technical expertise and capabilities
            </p>
            <div className="columns is-multiline is-variable is-4">
              {technicalStrengths.map((strength, index) => (
                <div key={index} className="column is-half">
                  <div style={{ 
                    padding: '1.5rem', 
                    background: 'rgba(72, 199, 116, 0.05)', 
                    borderRadius: '12px', 
                    border: '1px solid rgba(72, 199, 116, 0.2)',
                    height: '100%'
                  }}>
                    <div style={{ display: 'flex', alignItems: 'center', marginBottom: '1rem' }}>
                      <span style={{ fontSize: '2rem', marginRight: '0.8rem' }}>{strength.icon}</span>
                      <h3 style={{ color: '#e85d04', fontWeight: '600', fontSize: '1.1rem', margin: 0 }}>
                        {strength.category}
                      </h3>
                    </div>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
                      {strength.skills.map((skill, skillIndex) => (
                        <span key={skillIndex} style={{
                          backgroundColor: 'rgba(72, 199, 116, 0.15)',
                          color: '#f0f0f0',
                          padding: '0.4rem 0.8rem',
                          borderRadius: '8px',
                          fontSize: '0.85rem',
                          border: '1px solid rgba(72, 199, 116, 0.3)'
                        }}>
                          {skill}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </FadeInWrapper>

        <FadeInWrapper translateY={30} delay={475}>
          <div className="box" style={bubbleStyle}>
              <h2 className="title is-3 has-text-success-dark has-text-centered mb-6">Resume</h2>
              <p className="has-text-centered" style={{color: '#f0f0f0'}}>Download my resume.</p>
              <div className="buttons is-centered mt-4">
                <a className="button is-success" href="/files/Resume-Carter.docx" download="Resume-Carter.docx">Download Resume</a>
              </div>
          </div>
        </FadeInWrapper>

        <FadeInWrapper translateY={30} delay={500}>
          <div className="box" style={bubbleStyle}>
              <h2 className="title is-3 has-text-success-dark has-text-centered mb-6">Education & Professional Certifications</h2>
              
              <div className="columns is-variable is-6 is-multiline">
                {/* Education Section - Full Width */}
                <div className="column is-full">
                  <h3 className="title is-4 has-text-success has-text-centered mb-5" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}>
                    <span>🎓</span> Education
                  </h3>
                  <div className="columns is-variable is-4">
                    {education.map((edu, index) => (
                      <div key={index} className="column is-half">
                        <div style={{ 
                          padding: '1.5rem', 
                          background: 'linear-gradient(135deg, rgba(72, 199, 116, 0.08) 0%, rgba(72, 199, 116, 0.03) 100%)', 
                          borderRadius: '12px', 
                          border: '2px solid rgba(72, 199, 116, 0.25)',
                          height: '100%',
                          transition: 'transform 0.2s, box-shadow 0.2s',
                          boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)'
                        }}>
                          <div style={{ marginBottom: '0.8rem' }}>
                            <h4 style={{ color: '#e85d04', fontWeight: '700', fontSize: '1.15rem', marginBottom: '0.6rem', lineHeight: '1.3' }}>
                              {edu.degree}
                            </h4>
                            <p style={{ color: '#48c774', fontWeight: '600', fontSize: '1rem', marginBottom: '0.4rem' }}>
                              {edu.school}
                            </p>
                            <p style={{ 
                              color: '#a0a0a0', 
                              fontSize: '0.9rem', 
                              marginBottom: '0.8rem',
                              display: 'flex',
                              alignItems: 'center',
                              gap: '0.4rem'
                            }}>
                              <span>📅</span> {edu.year}
                            </p>
                          </div>
                          <p style={{ 
                            color: '#d0d0d0', 
                            fontSize: '0.95rem', 
                            lineHeight: '1.5',
                            borderTop: '1px solid rgba(72, 199, 116, 0.2)',
                            paddingTop: '0.8rem'
                          }}>
                            {edu.description}
                          </p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
                
                {/* Certifications Section - Full Width */}
                <div className="column is-full">
                  <h3 className="title is-4 has-text-success has-text-centered mb-5" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}>
                    <span>🏆</span> Professional Certifications & Expertise
                  </h3>
                  <div className="columns is-multiline is-variable is-4">
                    {certifications.map((cert, index) => {
                      const CertContent = (
                        <>
                          <div style={{ 
                            fontSize: '3rem', 
                            marginBottom: '1rem',
                            filter: 'drop-shadow(0 2px 4px rgba(0,0,0,0.2))'
                          }}>
                            {cert.icon}
                          </div>
                          <h4 style={{ 
                            color: '#f0f0f0', 
                            fontWeight: '700', 
                            fontSize: '1rem', 
                            marginBottom: '0.5rem',
                            lineHeight: '1.2'
                          }}>
                            {cert.title}
                          </h4>
                          <p style={{ 
                            color: '#a0a0a0', 
                            fontSize: '0.85rem',
                            fontWeight: '500'
                          }}>
                            {cert.issuer}
                          </p>
                        </>
                      );

                      const cardStyle = { 
                        padding: '1.5rem',
                        background: `linear-gradient(135deg, ${cert.color}15 0%, ${cert.color}05 100%)`,
                        borderRadius: '12px',
                        border: `2px solid ${cert.color}40`,
                        textAlign: 'center' as const,
                        height: '100%',
                        display: 'flex',
                        flexDirection: 'column' as const,
                        alignItems: 'center',
                        justifyContent: 'center',
                        transition: 'transform 0.2s, box-shadow 0.2s',
                        cursor: cert.credlyUrl ? 'pointer' : 'default',
                        boxShadow: `0 4px 12px ${cert.color}20`
                      };

                      return (
                        <div key={index} className="column is-half-tablet is-one-quarter-desktop">
                          {cert.credlyUrl ? (
                            <a 
                              href={cert.credlyUrl} 
                              target="_blank" 
                              rel="noopener noreferrer"
                              style={{ textDecoration: 'none' }}
                            >
                              <div 
                                style={cardStyle}
                                onMouseEnter={(e) => {
                                  e.currentTarget.style.transform = 'translateY(-5px)';
                                  e.currentTarget.style.boxShadow = `0 8px 20px ${cert.color}40`;
                                }}
                                onMouseLeave={(e) => {
                                  e.currentTarget.style.transform = 'translateY(0)';
                                  e.currentTarget.style.boxShadow = `0 4px 12px ${cert.color}20`;
                                }}
                              >
                                {CertContent}
                              </div>
                            </a>
                          ) : (
                            <div style={cardStyle}>
                              {CertContent}
                            </div>
                          )}
                        </div>
                      );
                    })}
                  </div>
                </div>

                {/* Call to Action */}
                <div className="column is-full">
                  <div style={{ 
                    textAlign: 'center', 
                    padding: '2rem',
                    background: 'rgba(72, 199, 116, 0.05)',
                    borderRadius: '12px',
                    border: '1px solid rgba(72, 199, 116, 0.2)'
                  }}>
                    <p style={{ color: '#f0f0f0', fontSize: '1.1rem', marginBottom: '1.5rem' }}>
                      Ready to work together on your next project?
                    </p>
                    <a href="/contact" className="button is-success is-medium">
                      <span className="icon">
                        <span>💼</span>
                      </span>
                      <span>Let&apos;s Work Together</span>
                    </a>
                  </div>
                </div>
              </div>
          </div>
        </FadeInWrapper>

      </div>
    </div>
  );
}

// frontend/src/app/about/about.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-about',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './about.component.html',
  styles: []
})
export class AboutComponent {
  philosophy = "I believe exceptional software is created at the intersection of technical excellence and human-centered design. My approach combines rigorous engineering practices with deep empathy for user needs, resulting in solutions that are not only functionally robust but genuinely valuable to those who use them.";
  
  bio = `I am a Computer Science graduate student at UW-La Crosse, focused on architecting intelligent systems that benefit society. AI is transforming the entire world, and I want to help ensure that transformation is positive, safe, and innovative.

  With extensive experience in AI Prompt Engineering and MEAN stack development, I build systems that bridge the gap between complex research and user-friendly applications. I have worked as an AI Trainer, optimizing machine learning models with precise programming and logical rigor. My commitment to helping others was shaped by my childhood volunteering at the Fond du Lac Food Pantry, a value I bring to every technical project I undertake.`;

  strategies = [
    { title: 'Requirements Analysis', desc: 'Thoroughly understanding project requirements and business goals to create a comprehensive development strategy.' },
    { title: 'Architecture & Design', desc: 'Designing scalable system architecture and intuitive user interfaces, focusing on performance and UX.' },
    { title: 'Clean Development', desc: 'Writing maintainable, secure code using modern best practices and industry-leading frameworks.' },
    { title: 'Testing & Reliability', desc: 'Conducting comprehensive testing and managing deployments to ensure robust, production-ready applications.' }
  ];

  strengths = [
    { category: 'Frontend', skills: ['React', 'Next.js', 'Angular', 'TypeScript', 'Tailwind', 'Bulma'] },
    { category: 'Backend', skills: ['Node.js', 'Express', 'Python', 'Java', 'C', 'RESTful APIs'] },
    { category: 'Database', skills: ['MySQL', 'Database Design', 'SQL Optimization', 'Data Modeling'] },
    { category: 'AI & Tools', skills: ['LLM Integration', 'Prompt Engineering', 'Git/GitHub', 'Code Review'] }
  ];

  certifications = [
    { title: 'Microsoft Office Specialist', issuer: 'Microsoft Certified Core', icon: '📄', color: '#0078D4', url: 'https://www.credly.com/badges/a53e0814-7906-43fc-99aa-87ca2d203a6e/public_url' },
    { title: 'Microsoft Word Specialist', issuer: 'Microsoft Certified', icon: '📝', color: '#2B579A', url: 'https://www.credly.com/badges/836e8596-1ad6-4190-a2b1-37f9183b6602/public_url' },
    { title: 'Microsoft Excel Specialist', issuer: 'Microsoft Certified', icon: '📊', color: '#217346', url: 'https://www.credly.com/badges/397e3a70-ab52-4d53-9025-10beb9a80472/public_url' },
    { title: 'Microsoft PowerPoint Specialist', issuer: 'Microsoft Certified', icon: '📽️', color: '#D24726', url: 'https://www.credly.com/badges/ac9b7a98-01df-4160-ab5c-b706f28120ff/public_url' },
    { title: 'Full-Stack Developer', issuer: 'Professional Experience', icon: '💻', color: '#8b5cf6' },
    { title: 'AI Integration Specialist', issuer: 'LLM & API Integration', icon: '🤖', color: '#06b6d4' },
    { title: 'Database Management', issuer: 'MySQL & SQL', icon: '🗄️', color: '#3273dc' },
    { title: 'Modern Web Development', issuer: 'React & Next.js', icon: '⚛️', color: '#61dafb' }
  ];

  education = [
    { degree: 'MS in Software Engineering', school: 'University of Wisconsin-La Crosse', period: 'Started 2023, Expected 2026' },
    { degree: 'BS in Computer Programming', school: 'University of Wisconsin-La Crosse', period: 'Completed 2025 (Accelerated)' }
  ];

  references = [
    { name: 'Professor Judi Becker', role: 'College Writing Professor', desc: 'Expert in professional writing and research methodologies.' },
    { name: 'Kim Braatz', role: 'Computer Science Teacher', desc: 'Mentor in mobile app development and web programming.' },
    { name: 'Jennifer King', role: 'MOS Instructor', desc: 'Instructor for Microsoft Office Specialist certifications.' }
  ];
}

<section class="section-spacing relative min-h-screen">
  <div class="blur-glow bg-blue-600/10 top-0 left-0"></div>

  <!-- Hero Section & Biometric Profile -->
  <div class="grid lg:grid-cols-2 gap-12 sm:gap-24 mb-24 sm:mb-48 items-center">
    <div scrollReveal [srX]="-30" [srY]="0" class="text-center lg:text-left">
      <h1 class="fluid-h1 font-black mb-8 sm:mb-12 gradient-text tracking-tighter">About My Vision</h1>
      <p class="text-xl md:text-2xl text-slate-400 leading-relaxed font-medium tracking-tight mb-12 sm:mb-16 max-w-2xl mx-auto lg:ml-0">
        {{ bio }}
      </p>
      <div class="flex flex-wrap gap-4 sm:gap-6 justify-center lg:justify-start">
        <div *ngFor="let edu of education; let i = index" scrollReveal [srDelay]="getStagger(i)" class="px-6 py-4 sm:px-8 sm:py-5 rounded-[1.5rem] sm:rounded-[2rem] bg-blue-600/5 border border-blue-600/10 backdrop-blur-3xl transition-all hover:bg-blue-600/10 duration-500">
          <span class="fluid-tiny font-black text-blue-500 uppercase tracking-[0.4em] block mb-2">Academic Credential</span>
          <span class="text-white font-black text-lg sm:text-xl tracking-tighter block leading-tight">{{ edu.degree }}</span>
          <span class="text-slate-500 text-xs sm:text-sm font-bold block mt-1">{{ edu.school }}</span>
          <span class="text-blue-500 font-bold text-[10px] uppercase tracking-widest mt-2 block">{{ edu.period }}</span>
        </div>
      </div>
    </div>

    <!-- Stylized Profile Image -->
    <div class="relative group mx-auto lg:ml-auto lg:mr-0 mt-8 lg:mt-0">
      <div class="absolute -inset-4 bg-gradient-to-br from-blue-600 to-blue-900 rounded-[3rem] sm:rounded-[4rem] blur-2xl opacity-20 group-hover:opacity-40 transition-opacity duration-700"></div>
      <div class="relative p-2 sm:p-3 rounded-[3rem] sm:rounded-[4rem] bg-slate-900/50 border border-white/10 backdrop-blur-3xl shadow-2xl transition-all duration-1000 group-hover:rotate-1 group-hover:scale-[1.02]">
        <img src="/assets/images/profile.jpg" alt="Carter Moyer"
             width="500" height="625"
             class="w-full max-w-[500px] h-auto rounded-[2.8rem] sm:rounded-[3.5rem] object-cover filter brightness-90 contrast-110 group-hover:brightness-100 transition-all duration-700">
      </div>
    </div>
  </div>

  <div class="grid lg:grid-cols-3 gap-16 sm:gap-32 mb-24 sm:mb-48">
    <!-- Left Column: Philosophy & Process -->
    <div class="lg:col-span-2 space-y-20 sm:space-y-32">
      <div class="space-y-6 sm:space-y-10">
        <h2 class="fluid-h2 font-black text-white tracking-tighter italic">Professional Philosophy</h2>
        <p class="text-slate-400 text-lg sm:text-2xl font-medium leading-relaxed sm:leading-loose max-w-4xl">
          {{ philosophy }}
          <br><br>
          <a routerLink="/projects" class="text-blue-500 hover:text-blue-400 font-black text-sm uppercase tracking-widest inline-flex items-center gap-2 group/link transition-all">
            Explore My Technical Case Studies
            <svg class="w-4 h-4 group-hover/link:translate-x-1 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3">
              <path stroke-linecap="round" stroke-linejoin="round" d="M13 7l5 5m0 0l-5 5m5-5H6"/>
            </svg>
          </a>
        </p>
      </div>

      <div class="space-y-10 sm:space-y-16">
        <h2 class="fluid-h2 font-black text-white tracking-tighter italic">Architectural Process</h2>
        <div class="grid sm:grid-cols-2 gap-6 sm:gap-10">
          <div *ngFor="let step of strategies; let i = index" scrollReveal [srDelay]="getStagger(i)" class="p-8 sm:p-12 rounded-[2rem] sm:rounded-[2.5rem] bg-slate-900/40 border border-white/5 hover:border-blue-600/30 transition-all duration-700 group">
            <h4 class="text-blue-500 font-black mb-4 sm:mb-6 fluid-label uppercase tracking-[0.4em] group-hover:text-blue-400 transition-colors">{{ step.title }}</h4>
            <p class="text-slate-400 text-sm sm:text-base leading-relaxed font-medium">{{ step.desc }}</p>
          </div>
        </div>
      </div>

      <div class="space-y-16 sm:space-y-24">
        <h2 class="fluid-h2 font-black text-white tracking-tighter italic">Professional Experience</h2>
        <div class="space-y-12 sm:space-y-20">
          <div *ngFor="let exp of experiences; let i = index" scrollReveal [srDelay]="getStagger(i)" class="relative pl-12 sm:pl-16 group">
            <!-- Timeline Line -->
            <div class="absolute left-0 top-0 bottom-0 w-px bg-gradient-to-b from-blue-600 via-blue-900 to-transparent opacity-30 group-hover:opacity-100 transition-opacity duration-700"></div>
            <div class="absolute left-[-4px] top-2 w-2 h-2 rounded-full bg-blue-600 shadow-[0_0_15px_rgba(37,99,235,0.8)] group-hover:scale-150 transition-transform duration-500"></div>
            
            <div class="space-y-4 sm:space-y-6">
              <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <h3 class="text-2xl sm:text-3xl font-black text-white tracking-tighter group-hover:text-blue-400 transition-colors">{{ exp.role }}</h3>
                <span class="fluid-tiny font-black text-blue-500 uppercase tracking-[0.3em] bg-blue-600/5 px-4 py-2 rounded-xl border border-blue-600/10">{{ exp.period }}</span>
              </div>
              <p class="text-slate-400 font-bold text-sm sm:text-lg uppercase tracking-widest">{{ exp.company }}</p>
              <ul class="space-y-3 sm:space-y-4">
                <li *ngFor="let bullet of exp.bullets" class="flex gap-4 text-slate-400 text-sm sm:text-base leading-relaxed font-medium">
                  <span class="text-blue-600 font-black mt-1">/</span>
                  {{ bullet }}
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="space-y-10 sm:space-y-16">
        <h2 class="fluid-h2 font-black text-white tracking-tighter italic">Strategic References</h2>
        @defer (on viewport) {
          <div class="grid sm:grid-cols-2 gap-12 sm:gap-10 mt-8 sm:mt-0">
            <div *ngFor="let ref of references; let i = index" scrollReveal [srDelay]="getStagger(i)" class="p-8 sm:p-12 rounded-[2rem] sm:rounded-[2.5rem] bg-blue-900/10 border border-blue-800/20 italic relative group hover:bg-blue-900/20 transition-all duration-500">
              <div class="absolute -top-4 -left-4 sm:-top-6 sm:-left-6 w-12 h-12 sm:w-16 sm:h-16 bg-blue-700 rounded-2xl sm:rounded-3xl flex items-center justify-center text-white text-2xl sm:text-3xl font-black not-italic shadow-2xl shadow-blue-900/40 group-hover:scale-110 transition-transform duration-500">"</div>
              <h4 class="text-white font-black not-italic mb-2 text-xl sm:text-2xl tracking-tighter">{{ ref.name }}</h4>
              <p class="text-blue-500 font-bold text-xs not-italic mb-6 sm:mb-8 uppercase tracking-[0.3em]">{{ ref.role }}</p>
              <p class="text-slate-300 text-base sm:text-lg not-italic leading-relaxed font-medium">"{{ ref.desc }}"</p>
            </div>
          </div>
        } @placeholder {
          <div class="h-48 rounded-[2rem] bg-slate-900/20 animate-pulse" aria-hidden="true"></div>
        }
      </div>
    </div>

    <!-- Right Column: Skills & Certs -->
    @defer (on viewport) {
    <div class="space-y-12 sm:space-y-24">
      <div class="p-8 sm:p-12 rounded-[2.5rem] sm:rounded-[3rem] bg-slate-900/60 border border-white/5 space-y-12 sm:space-y-16 shadow-2xl backdrop-blur-2xl">
        <h2 class="text-2xl sm:text-3xl font-black text-white tracking-tighter italic">Technical Mastery</h2>
        <div *ngFor="let s of strengths" class="space-y-6 sm:space-y-8">
          <h4 class="fluid-label font-black text-slate-500 uppercase tracking-[0.5em]">{{ s.category }}</h4>
          <div class="flex flex-wrap gap-3 sm:gap-4">
            <span *ngFor="let skill of s.skills" class="px-4 py-2 sm:px-5 sm:py-2.5 rounded-xl bg-slate-950 text-slate-400 text-[10px] sm:text-xs font-black border border-white/10 hover:border-blue-600/50 hover:text-white hover:bg-blue-950 transition-all duration-500">
              {{ skill }}
            </span>
          </div>
        </div>
      </div>

      <div class="p-8 sm:p-12 rounded-[2.5rem] sm:rounded-[3rem] bg-blue-700/5 border border-blue-500/10 space-y-10 sm:space-y-12">
        <h2 class="text-2xl sm:text-3xl font-black text-white tracking-tighter italic">Credentials</h2>
        <div class="space-y-8 sm:space-y-10">
          <div *ngFor="let cert of certifications" class="group">
            <a *ngIf="cert.url" [href]="cert.url" target="_blank" rel="noopener noreferrer" class="flex items-center gap-6 sm:gap-8 cursor-pointer">
              <span class="text-4xl sm:text-5xl group-hover:scale-125 transition-transform duration-700 shrink-0">{{ cert.icon }}</span>
              <div class="flex flex-col gap-1">
                <h4 class="text-base sm:text-lg font-black text-white group-hover:text-blue-400 transition-colors tracking-tight">{{ cert.title }}</h4>
                <p class="fluid-tiny font-black text-slate-500 uppercase tracking-[0.4em]">{{ cert.issuer }}</p>
              </div>
            </a>
            <div *ngIf="!cert.url" class="flex items-center gap-6 sm:gap-8">
              <span class="text-4xl sm:text-5xl shrink-0">{{ cert.icon }}</span>
              <div class="flex flex-col gap-1">
                <h4 class="text-base sm:text-lg font-black text-white tracking-tight">{{ cert.title }}</h4>
                <p class="fluid-tiny font-black text-slate-500 uppercase tracking-[0.4em]">{{ cert.issuer }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    } @placeholder {
      <div class="h-64 rounded-[3rem] bg-slate-900/20 animate-pulse" aria-hidden="true"></div>
    }
  </div>

  <!-- Portfolios & Resume Call to Action -->
  <div scrollReveal [srDelay]="0.1" class="p-12 sm:p-24 rounded-[2.5rem] sm:rounded-[4rem] bg-gradient-to-br from-blue-900/20 via-blue-950/5 to-transparent border border-blue-900/30 text-center relative overflow-hidden backdrop-blur-3xl">
    <div class="absolute -bottom-40 -right-40 w-[500px] h-[500px] bg-blue-600/10 blur-[150px] rounded-full"></div>
    <h2 class="fluid-h1 font-black text-white mb-8 sm:mb-10 tracking-tighter italic">Documentation Archive</h2>
    <p class="text-slate-400 text-lg sm:text-2xl font-medium mb-12 sm:mb-16 max-w-3xl mx-auto leading-relaxed tracking-tight">Access comprehensive research archives, creative writing portfolios, and my validated technical resume.</p>
    <div class="flex flex-wrap justify-center gap-6 sm:gap-8 relative z-10">
      <a href="https://smallpdf.com/file#s=2d6f0249-75f9-4dd1-80bb-8076bccb2ae0" target="_blank" class="px-10 py-5 sm:px-12 sm:py-6 rounded-2xl bg-white/5 text-slate-200 font-black uppercase tracking-[0.2em] text-[10px] sm:text-xs hover:bg-white/10 transition-all border border-white/10 backdrop-blur-3xl flex items-center justify-center min-h-[44px]">Research Archive</a>
      <a href="https://smallpdf.com/file#s=ed812670-2631-498a-abbe-1645e40d998f" target="_blank" class="px-10 py-5 sm:px-12 sm:py-6 rounded-2xl bg-white/5 text-slate-200 font-black uppercase tracking-[0.2em] text-[10px] sm:text-xs hover:bg-white/10 transition-all border border-white/10 backdrop-blur-3xl flex items-center justify-center min-h-[44px]">Creative Portfolio</a>
      <a href="https://smallpdf.com/file#s=be5a9840-50a1-4d9c-96e2-c0a03ead3010" target="_blank" class="primary-btn shrink-0 flex items-center justify-center min-h-[44px]">Download Resume</a>
    </div>
  </div>
</section>
